# Generated by Django 3.0.5 on 2020-07-05 02:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0020_auto_20200705_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(related_name='product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 9, 14, 21, 369307)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 9, 14, 21, 373296)),
        ),
    ]
