# Generated by Django 3.0.7 on 2020-07-09 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200709_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 0, 0, 813238)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 0, 0, 809222)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 0, 0, 812241)),
        ),
    ]
