# Generated by Django 3.0.7 on 2020-07-09 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200709_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 27, 6, 938067)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 27, 6, 935042)),
        ),
        migrations.AlterField(
            model_name='propertylinkyoutobe',
            name='linkSource',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 27, 6, 938067)),
        ),
    ]
