# Generated by Django 3.0.7 on 2020-07-09 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20200709_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 29, 527558)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 29, 524534)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 29, 526561)),
        ),
    ]
