# Generated by Django 3.0.3 on 2020-07-14 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20200714_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 22, 39, 46, 246702)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 22, 39, 46, 242706)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 22, 39, 46, 245704)),
        ),
    ]
