# Generated by Django 3.0.3 on 2020-06-16 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='time_join',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 20, 48, 13, 813528)),
        ),
    ]
