# Generated by Django 3.0.7 on 2020-07-05 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200705_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time_join',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 5, 18, 59, 42, 964805), null=True),
        ),
    ]
