# Generated by Django 3.0.5 on 2020-07-04 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous_people', '0010_auto_20200704_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 0, 9, 20, 833178)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 0, 9, 20, 923935)),
        ),
    ]
