# Generated by Django 3.0.5 on 2020-07-04 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous_people', '0015_auto_20200705_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='famous',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='famous',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 1, 55, 0, 911901)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 1, 55, 1, 2659)),
        ),
    ]
