# Generated by Django 3.0.5 on 2020-07-05 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous_people', '0018_auto_20200705_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 9, 10, 39, 942621)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 9, 10, 39, 945613)),
        ),
        migrations.DeleteModel(
            name='Famous_Like',
        ),
    ]
