# Generated by Django 3.0.5 on 2020-07-05 02:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('famous_people', '0019_auto_20200705_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='famous',
            name='like',
            field=models.ManyToManyField(related_name='famous', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='famous',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 9, 14, 21, 357340)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 9, 14, 21, 362326)),
        ),
    ]
