# Generated by Django 3.0.7 on 2020-07-05 11:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('famous_people', '0021_auto_20200705_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 18, 38, 7, 197728)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 18, 38, 7, 199723)),
        ),
        migrations.CreateModel(
            name='CommentFaMous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyFamous', models.TextField(blank=True, null=True)),
                ('dateFamous', models.DateTimeField(default=datetime.datetime(2020, 7, 5, 18, 38, 7, 200720))),
                ('authorFamous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postFamous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsFamous', to='famous_people.Famous')),
                ('replyFamous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repliesFamous', to='famous_people.CommentFaMous')),
            ],
            options={
                'ordering': ('dateFamous',),
            },
        ),
    ]
