# Generated by Django 3.0.7 on 2020-07-09 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous_people', '0027_auto_20200709_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfamous',
            name='dateFamous',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 29, 522571)),
        ),
        migrations.AlterField(
            model_name='famous',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 29, 519580)),
        ),
        migrations.AlterField(
            model_name='propertytime',
            name='timeDetail',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 17, 28, 29, 522571)),
        ),
    ]
